name: gestionale_desktop
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.2.5
  dio: ^5.5.0+1
  flutter_dotenv: ^6.0.0
  supabase_flutter: ^2.10.3
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  intl: ^0.20.2
  file_picker: ^10.3.3
  csv: ^6.0.0
  flex_color_scheme: ^8.3.0
  adaptive_breakpoints: ^0.1.6
  data_table_2: ^2.5.10
  google_fonts: ^6.2.1
  phosphor_flutter: ^2.1.0
  table_calendar: ^3.0.9
  fl_chart: ^0.68.0
  printing: ^5.14.2
  pdf: ^3.11.3
  web: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/design system/theme/colors/neutral_inline.json
    - lib/design system/theme/colors/neutral_rgb.json
    # Asset con l'elenco dei tribunali/fori raggruppati per regione
    - lib/features/courtroom.json
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.otf
          weight: 600
